// @tier: community

import 'package:seafoundry_app/models/inventory/physical_form_config.dart';

/// Hardcoded physical form configuration data.
///
/// This replaces the former YAML-based config/organism_physical_forms.yaml.
/// Structure: organism kind key -> life stage key -> list of PhysicalFormConfig.
///
/// Version: v8  (matches the last YAML version)
const String physicalFormDataVersion = 'v8';

/// All physical form configs keyed by (organismKind.name, lifeStage.name).
///
/// Access pattern:
///   `physicalFormData['coral']?['gamete']` returns a `List<PhysicalFormConfig>`
final Map<String, Map<String, List<PhysicalFormConfig>>> physicalFormData = {
  'coral': {
    // ── Gamete ──────────────────────────────────────────────────────────
    'gamete': const [
      PhysicalFormConfig(
        id: 'liquid_suspension',
        displayName: 'Liquid Suspension (Vial/Aliquot)',
        countingMode: InventoryCountingMode.volumetric,
        measurementUnit: 'milliliters',
        sizeBands: [
          SizeBandConfig(
            id: 'xs',
            label: 'Extra Small (0.5mL)',
            volumeMm3: 500,
            estimatedIndividuals: 50000,
            sortOrder: 1,
            enableCount: false,
            enableVolume: true,
            enableTissueArea: false,
            volumeLabel: 'Sample Volume (mL)',
          ),
          SizeBandConfig(
            id: 'small',
            label: 'Small (1mL)',
            volumeMm3: 1000,
            estimatedIndividuals: 100000,
            sortOrder: 2,
            enableCount: false,
            enableVolume: true,
            enableTissueArea: false,
            volumeLabel: 'Sample Volume (mL)',
          ),
          SizeBandConfig(
            id: 'medium',
            label: 'Medium (5mL)',
            volumeMm3: 5000,
            estimatedIndividuals: 500000,
            sortOrder: 3,
            enableCount: false,
            enableVolume: true,
            enableTissueArea: false,
            volumeLabel: 'Sample Volume (mL)',
          ),
          SizeBandConfig(
            id: 'large',
            label: 'Large (10mL)',
            volumeMm3: 10000,
            estimatedIndividuals: 1000000,
            sortOrder: 4,
            enableCount: false,
            enableVolume: true,
            enableTissueArea: false,
            volumeLabel: 'Sample Volume (mL)',
          ),
          SizeBandConfig(
            id: 'xl',
            label: 'Extra Large (50mL)',
            volumeMm3: 50000,
            estimatedIndividuals: 5000000,
            sortOrder: 5,
            enableCount: false,
            enableVolume: true,
            enableTissueArea: false,
            volumeLabel: 'Sample Volume (mL)',
          ),
        ],
      ),
    ],

    // ── Embryo ─────────────────────────────────────────────────────────
    'embryo': const [
      PhysicalFormConfig(
        id: 'liquid_suspension',
        displayName: 'Liquid Suspension (Culture Vessel)',
        countingMode: InventoryCountingMode.volumetric,
        measurementUnit: 'milliliters',
        sizeBands: [
          SizeBandConfig(
            id: 'small',
            label: 'Small (10mL)',
            volumeMm3: 10000,
            estimatedIndividuals: 4,
            sortOrder: 1,
            enableCount: false,
            enableVolume: true,
            enableTissueArea: false,
            volumeLabel: 'Sample Volume (mL)',
          ),
          SizeBandConfig(
            id: 'medium',
            label: 'Medium (50mL)',
            volumeMm3: 50000,
            estimatedIndividuals: 21,
            sortOrder: 2,
            enableCount: false,
            enableVolume: true,
            enableTissueArea: false,
            volumeLabel: 'Sample Volume (mL)',
          ),
          SizeBandConfig(
            id: 'large',
            label: 'Large (100mL)',
            volumeMm3: 100000,
            estimatedIndividuals: 42,
            sortOrder: 3,
            enableCount: false,
            enableVolume: true,
            enableTissueArea: false,
            volumeLabel: 'Sample Volume (mL)',
          ),
          SizeBandConfig(
            id: 'xl',
            label: 'Extra Large (500mL)',
            volumeMm3: 500000,
            estimatedIndividuals: 210,
            sortOrder: 4,
            enableCount: false,
            enableVolume: true,
            enableTissueArea: false,
            volumeLabel: 'Sample Volume (mL)',
          ),
        ],
      ),
    ],

    // ── Larva ──────────────────────────────────────────────────────────
    'larva': const [
      PhysicalFormConfig(
        id: 'liquid_suspension',
        displayName: 'Liquid Suspension (Larval Tank)',
        countingMode: InventoryCountingMode.volumetric,
        measurementUnit: 'milliliters',
        sizeBands: [
          SizeBandConfig(
            id: 'small',
            label: 'Small (100mL)',
            volumeMm3: 100000,
            estimatedIndividuals: 50,
            sortOrder: 1,
            enableCount: false,
            enableVolume: true,
            enableTissueArea: false,
            volumeLabel: 'Sample Volume (mL)',
          ),
          SizeBandConfig(
            id: 'medium',
            label: 'Medium (500mL)',
            volumeMm3: 500000,
            estimatedIndividuals: 250,
            sortOrder: 2,
            enableCount: false,
            enableVolume: true,
            enableTissueArea: false,
            volumeLabel: 'Sample Volume (mL)',
          ),
          SizeBandConfig(
            id: 'large',
            label: 'Large (1L)',
            volumeMm3: 1000000,
            estimatedIndividuals: 500,
            sortOrder: 3,
            enableCount: false,
            enableVolume: true,
            enableTissueArea: false,
            volumeLabel: 'Sample Volume (mL)',
          ),
          SizeBandConfig(
            id: 'xl',
            label: 'Extra Large (5L)',
            volumeMm3: 5000000,
            estimatedIndividuals: 2500,
            sortOrder: 4,
            enableCount: false,
            enableVolume: true,
            enableTissueArea: false,
            volumeLabel: 'Sample Volume (mL)',
          ),
        ],
      ),
    ],

    // ── Juvenile ───────────────────────────────────────────────────────
    'juvenile': const [
      PhysicalFormConfig(
        id: 'settlement_substrate',
        displayName: 'Settlement Substrate',
        countingMode: InventoryCountingMode.individual,
        measurementUnit: 'substrates',
        sizeBands: [
          SizeBandConfig(
            id: 'xs',
            label: 'Extra Small (10x10cm)',
            volumeMm3: 0,
            estimatedIndividuals: 250,
            sortOrder: 1,
            enableCount: true,
            enableVolume: false,
            enableTissueArea: true,
            countLabel: 'Number of Substrates',
            volumeLabel: 'Substrate Volume',
            tissueAreaLabel: 'Settlement Coverage (cm\u00b2)',
            defaultTissueAreaCm2: 4,
          ),
          SizeBandConfig(
            id: 'small',
            label: 'Small (~15cm accross)',
            volumeMm3: 0,
            estimatedIndividuals: 500,
            sortOrder: 2,
            enableCount: true,
            enableVolume: false,
            enableTissueArea: true,
            countLabel: 'Number of Substrates',
            volumeLabel: 'Substrate Volume',
            tissueAreaLabel: 'Settlement Coverage (cm\u00b2)',
            defaultTissueAreaCm2: 9,
          ),
          SizeBandConfig(
            id: 'medium',
            label: 'Medium (20x20cm)',
            volumeMm3: 0,
            estimatedIndividuals: 1000,
            sortOrder: 3,
            enableCount: true,
            enableVolume: false,
            enableTissueArea: true,
            countLabel: 'Number of Substrates',
            volumeLabel: 'Substrate Volume',
            tissueAreaLabel: 'Settlement Coverage (cm\u00b2)',
            defaultTissueAreaCm2: 15,
          ),
          SizeBandConfig(
            id: 'large',
            label: 'Large (30x30cm)',
            volumeMm3: 0,
            estimatedIndividuals: 2000,
            sortOrder: 4,
            enableCount: true,
            enableVolume: false,
            enableTissueArea: true,
            countLabel: 'Number of Substrates',
            volumeLabel: 'Substrate Volume',
            tissueAreaLabel: 'Settlement Coverage (cm\u00b2)',
            defaultTissueAreaCm2: 34,
          ),
          SizeBandConfig(
            id: 'xl',
            label: 'Extra Large (40x40cm)',
            volumeMm3: 0,
            estimatedIndividuals: 4000,
            sortOrder: 5,
            enableCount: true,
            enableVolume: false,
            enableTissueArea: true,
            countLabel: 'Number of Substrates',
            volumeLabel: 'Substrate Volume',
            tissueAreaLabel: 'Settlement Coverage (cm\u00b2)',
            defaultTissueAreaCm2: 61,
          ),
        ],
      ),
      PhysicalFormConfig(
        id: 'mounted_individual',
        displayName: 'Mounted Individual (Plug)',
        countingMode: InventoryCountingMode.individual,
        measurementUnit: 'count',
        sizeBands: [
          SizeBandConfig(
            id: 'xs',
            label: 'Extra Small (<1cm)',
            volumeMm3: 0,
            sortOrder: 1,
            enableCount: true,
            enableVolume: false,
            enableTissueArea: true,
            countLabel: 'Number of Plugs',
            volumeLabel: 'Plug Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 2,
          ),
          SizeBandConfig(
            id: 'small',
            label: 'Small (1-2cm)',
            volumeMm3: 0,
            sortOrder: 2,
            enableCount: true,
            enableVolume: false,
            enableTissueArea: true,
            countLabel: 'Number of Plugs',
            volumeLabel: 'Plug Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 4,
          ),
          SizeBandConfig(
            id: 'medium',
            label: 'Medium (2-3cm)',
            volumeMm3: 0,
            sortOrder: 3,
            enableCount: true,
            enableVolume: false,
            enableTissueArea: true,
            countLabel: 'Number of Plugs',
            volumeLabel: 'Plug Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 10,
          ),
          SizeBandConfig(
            id: 'large',
            label: 'Large (3-5cm)',
            volumeMm3: 0,
            sortOrder: 4,
            enableCount: true,
            enableVolume: false,
            enableTissueArea: true,
            countLabel: 'Number of Plugs',
            volumeLabel: 'Plug Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 25,
          ),
          SizeBandConfig(
            id: 'xl',
            label: 'Extra Large (5-7cm)',
            volumeMm3: 0,
            sortOrder: 5,
            enableCount: true,
            enableVolume: false,
            enableTissueArea: true,
            countLabel: 'Number of Plugs',
            volumeLabel: 'Plug Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 57,
          ),
        ],
      ),
    ],

    // ── Adult ──────────────────────────────────────────────────────────
    'adult': const [
      PhysicalFormConfig(
        id: 'mounted_individual',
        displayName: 'Mounted Individual (Plug)',
        countingMode: InventoryCountingMode.individual,
        measurementUnit: 'count',
        sizeBands: [
          SizeBandConfig(
            id: 'small',
            label: 'Small (2-4cm)',
            volumeMm3: 7069,
            sortOrder: 1,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Number of Plugs',
            volumeLabel: 'Plug Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 14,
          ),
          SizeBandConfig(
            id: 'medium',
            label: 'Medium (4-8cm)',
            volumeMm3: 56549,
            sortOrder: 2,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Number of Plugs',
            volumeLabel: 'Plug Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 57,
          ),
          SizeBandConfig(
            id: 'large',
            label: 'Large (8-12cm)',
            volumeMm3: 261799,
            sortOrder: 3,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Number of Plugs',
            volumeLabel: 'Plug Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 157,
          ),
          SizeBandConfig(
            id: 'xl',
            label: 'Extra Large (12-16cm)',
            volumeMm3: 718378,
            sortOrder: 4,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Number of Plugs',
            volumeLabel: 'Plug Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 308,
          ),
        ],
      ),
      PhysicalFormConfig(
        id: 'shared_substrate',
        displayName: 'Shared Substrate',
        countingMode: InventoryCountingMode.individual,
        measurementUnit: 'substrates',
        sizeBands: [
          SizeBandConfig(
            id: 'small',
            label: 'Small (0-5 individuals, ~70cm)',
            volumeMm3: 10000,
            estimatedIndividuals: 5,
            sortOrder: 1,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Number of Substrates',
            volumeLabel: 'Substrate Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 15,
          ),
          SizeBandConfig(
            id: 'medium',
            label: 'Medium (5-10 individuals, ~90cm)',
            volumeMm3: 20000,
            estimatedIndividuals: 10,
            sortOrder: 2,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Number of Substrates',
            volumeLabel: 'Substrate Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 60,
          ),
          SizeBandConfig(
            id: 'large',
            label: 'Large (10-15 individuals, ~100cm)',
            volumeMm3: 40000,
            estimatedIndividuals: 15,
            sortOrder: 3,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Number of Substrates',
            volumeLabel: 'Substrate Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 167,
          ),
          SizeBandConfig(
            id: 'xl',
            label: 'Extra Large (15-20 individuals, >100cm)',
            volumeMm3: 80000,
            estimatedIndividuals: 20,
            sortOrder: 4,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Number of Substrates',
            volumeLabel: 'Substrate Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 327,
          ),
        ],
      ),
      PhysicalFormConfig(
        id: 'fragment',
        displayName: 'Fragment (Clipping)',
        countingMode: InventoryCountingMode.individual,
        measurementUnit: 'count',
        sizeBands: [
          SizeBandConfig(
            id: 'small',
            label: 'Small (0-5cm)',
            volumeMm3: 4091,
            sortOrder: 1,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Number of Fragments',
            volumeLabel: 'Fragment Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 10,
          ),
          SizeBandConfig(
            id: 'medium',
            label: 'Medium (5-10cm)',
            volumeMm3: 110447,
            sortOrder: 2,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Number of Fragments',
            volumeLabel: 'Fragment Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 88,
          ),
          SizeBandConfig(
            id: 'large',
            label: 'Large (10-20cm)',
            volumeMm3: 883573,
            sortOrder: 3,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Number of Fragments',
            volumeLabel: 'Fragment Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 353,
          ),
          SizeBandConfig(
            id: 'xl',
            label: 'Extra Large (20-30cm)',
            volumeMm3: 4090615,
            sortOrder: 4,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Number of Fragments',
            volumeLabel: 'Fragment Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 982,
          ),
        ],
      ),
      PhysicalFormConfig(
        id: 'colony',
        displayName: 'Colony',
        countingMode: InventoryCountingMode.individual,
        measurementUnit: 'count',
        sizeBands: [
          SizeBandConfig(
            id: 'small',
            label: 'Small (10-20cm)',
            volumeMm3: 883573,
            sortOrder: 1,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Colony Count',
            volumeLabel: 'Colony Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 353,
          ),
          SizeBandConfig(
            id: 'medium',
            label: 'Medium (20-40cm)',
            volumeMm3: 7068583,
            sortOrder: 2,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Colony Count',
            volumeLabel: 'Colony Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 1414,
          ),
          SizeBandConfig(
            id: 'large',
            label: 'Large (40-60cm)',
            volumeMm3: 32724923,
            sortOrder: 3,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Colony Count',
            volumeLabel: 'Colony Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 3927,
          ),
          SizeBandConfig(
            id: 'xl',
            label: 'Extra Large (60-80cm)',
            volumeMm3: 89797190,
            sortOrder: 4,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Colony Count',
            volumeLabel: 'Colony Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 7697,
          ),
        ],
      ),
      PhysicalFormConfig(
        id: 'spawning_colony',
        displayName: 'Spawning Colony',
        countingMode: InventoryCountingMode.individual,
        measurementUnit: 'count',
        sizeBands: [
          SizeBandConfig(
            id: 'small',
            label: 'Small (40-60cm)',
            volumeMm3: 32724923,
            sortOrder: 1,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Colony Count',
            volumeLabel: 'Colony Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 3927,
          ),
          SizeBandConfig(
            id: 'medium',
            label: 'Medium (60-80cm)',
            volumeMm3: 89797190,
            sortOrder: 2,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Colony Count',
            volumeLabel: 'Colony Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 7697,
          ),
          SizeBandConfig(
            id: 'large',
            label: 'Large (80-100cm)',
            volumeMm3: 190851754,
            sortOrder: 3,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Colony Count',
            volumeLabel: 'Colony Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 12723,
          ),
          SizeBandConfig(
            id: 'xl',
            label: 'Extra Large (>100cm)',
            volumeMm3: 261799388,
            sortOrder: 4,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Colony Count',
            volumeLabel: 'Colony Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 15708,
          ),
        ],
      ),
    ],

    // ── Broodstock ─────────────────────────────────────────────────────
    'broodstock': const [
      PhysicalFormConfig(
        id: 'spawning_colony',
        displayName: 'Spawning Colony (Broodstock)',
        countingMode: InventoryCountingMode.individual,
        measurementUnit: 'count',
        sizeBands: [
          SizeBandConfig(
            id: 'small',
            label: 'Small (40-60cm)',
            volumeMm3: 32724923,
            sortOrder: 1,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Colony Count',
            volumeLabel: 'Colony Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 3927,
          ),
          SizeBandConfig(
            id: 'medium',
            label: 'Medium (60-80cm)',
            volumeMm3: 89797190,
            sortOrder: 2,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Colony Count',
            volumeLabel: 'Colony Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 7697,
          ),
          SizeBandConfig(
            id: 'large',
            label: 'Large (80-100cm)',
            volumeMm3: 190851754,
            sortOrder: 3,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Colony Count',
            volumeLabel: 'Colony Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 12723,
          ),
          SizeBandConfig(
            id: 'xl',
            label: 'Extra Large (>100cm)',
            volumeMm3: 261799388,
            sortOrder: 4,
            enableCount: true,
            enableVolume: true,
            enableTissueArea: true,
            countLabel: 'Colony Count',
            volumeLabel: 'Colony Volume',
            tissueAreaLabel: 'Live Tissue Area (cm\u00b2)',
            defaultTissueAreaCm2: 15708,
          ),
        ],
      ),
    ],
  },
};
