import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:seafoundry_community/models/species.dart';

/// Centralized helper for allocating Provenance IDs so every organism
/// can rely on a deterministic, per-species identifier. The service stores the
/// next counter inside `provenanceIds/{speciesId}` documents which mirrors the
/// legacy genet implementation but keeps the logic reusable across repositories.
class ProvenanceIdService {
  ProvenanceIdService({
    required FirebaseFirestore firestore,
  }) : _firestore = firestore;

  static const String _collectionPath = 'provenanceIds';

  final FirebaseFirestore _firestore;

  /// Pattern matching auto-generated provenance IDs produced by this service.
  static final RegExp autoGeneratedPattern = RegExp(r'^PID-[A-Z]{2,4}-\d{4,}$');

  /// Returns true if the given provenance ID was auto-generated by this service.
  static bool isAutoGenerated(String provenanceId) =>
      autoGeneratedPattern.hasMatch(provenanceId.trim());

  /// Previews the next Provenance ID without incrementing the counter.
  /// Returns the formatted PID that *would* be generated on next creation.
  Future<String> previewNextProvenanceId({required String speciesId}) async {
    final normalized = speciesId.trim();
    if (normalized.isEmpty) {
      throw ArgumentError.value(speciesId, 'speciesId', 'Cannot be empty');
    }
    final doc = _firestore
        .collection(_collectionPath)
        .doc(normalized);
    final snapshot = await doc.get();
    int nextValue = 1;
    if (snapshot.exists && snapshot.data()?['next'] != null) {
      final data = snapshot.data();
      if (data != null && data['next'] is int) {
        nextValue = (data['next'] as int) + 1;
      }
    }
    return _formatProvenanceId(speciesId: normalized, counter: nextValue);
  }

  /// Returns the next Provenance ID for the provided [speciesId]. IDs are formatted as
  /// `PID-$speciesCode-$counter` (e.g., `PID-ACER-0001`). Counters are isolated per
  /// species so simultaneous requests for different species never collide.
  Future<String> nextProvenanceId({required String speciesId}) async {
    final normalized = speciesId.trim();
    if (normalized.isEmpty) {
      throw ArgumentError.value(speciesId, 'speciesId', 'Cannot be empty');
    }
    return _firestore.runTransaction((txn) async {
      final doc = _firestore
          .collection(_collectionPath)
          .doc(normalized);
      final snapshot = await txn.get(doc);
      int nextValue = 1;
      if (snapshot.exists && snapshot.data()?['next'] != null) {
        final data = snapshot.data();
        if (data != null && data['next'] is int) {
          nextValue = (data['next'] as int) + 1;
        }
        txn.update(doc, {
          'next': nextValue,
          'updatedAt': FieldValue.serverTimestamp(),
        });
      } else {
        txn.set(doc, {
          'next': nextValue,
          'createdAt': FieldValue.serverTimestamp(),
          'updatedAt': FieldValue.serverTimestamp(),
        });
      }
      return _formatProvenanceId(speciesId: normalized, counter: nextValue);
    });
  }

  /// Formats the human-readable Provenance ID string. Repositories can call this when
  /// backfilling existing counters or parsing identifiers for display.
  static String formatProvenanceId({required String speciesId, required int counter}) {
    return _formatProvenanceId(speciesId: speciesId, counter: counter);
  }

  static String _formatProvenanceId({required String speciesId, required int counter}) {
    final code = _speciesSlug(speciesId);
    final padded = counter.toString().padLeft(4, '0');
    return 'PID-$code-$padded';
  }

  /// Derive a short, human-friendly slug from a species identifier.
  ///
  /// Rules:
  /// - Strip leading `species_`/underscores and non-letter characters
  /// - Prefer the first capitalized token when CamelCased (e.g., Acer from AcerRubrum)
  /// - Fallback to the first token when snake/kebab case
  /// - Truncate to 4 characters, uppercase
  static String _speciesSlug(String speciesId) {
    final trimmed = speciesId.trim();
    if (trimmed.isEmpty) return 'UNK';

    final species = Species.lookupById(trimmed);
    if (species != null) {
      final code = species.code.trim();
      final hasCustomCode = code.isNotEmpty &&
          code.toUpperCase() != species.id.toUpperCase();
      if (hasCustomCode) {
        return _normalizeCode(code);
      }
    }

    final withoutPrefix = trimmed.replaceFirst(
      RegExp(r'^species[_-]+', caseSensitive: false),
      '',
    );
    final cleaned = withoutPrefix.replaceAll(RegExp(r'[^A-Za-z]'), ' ');
    final tokens = cleaned
        .split(RegExp(r'[\s_]+'))
        .where((token) => token.isNotEmpty)
        .toList();
    var base = tokens.isNotEmpty ? tokens.first : cleaned;

    final camelMatches = RegExp(r'[A-Z][a-z]*').allMatches(base);
    final isAllCaps = RegExp(r'^[A-Z]+$').hasMatch(base);
    if (!isAllCaps && camelMatches.isNotEmpty) {
      base = camelMatches.first.group(0)!;
    }

    final normalized = base.toLowerCase();
    if (normalized.isEmpty) return 'UNK';
    final truncated = normalized.length <= 4
        ? normalized
        : normalized.substring(0, 4);
    return truncated.toUpperCase();
  }

  static String _normalizeCode(String code) {
    final cleaned = code.trim();
    if (cleaned.isEmpty) return 'UNK';
    final upper = cleaned.toUpperCase();
    final truncated = upper.length <= 4 ? upper : upper.substring(0, 4);
    return truncated;
  }
}
